version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
