name: Lint and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        shell: bash
        run: |
          sudo apt install shellcheck -y
          shellcheck *.sh
  test:
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install current Bash on macOS
        if: runner.os == 'macOS'
        run: brew install bash curl

      - name: Test
        shell: bash
        env:
          GIT_USERNAME: ${{ vars.GIT_FAKE_USERNAME }}
          GIT_EMAIL: ${{ vars.GIT_FAKE_EMAIL }}
          GPG_KEY_ID: ${{ vars.GPG_FAKE_KEY_ID }}
          GPG_KEY: ${{ vars.GPG_FAKE_KEY }}
          GPG_PASSPHRASE: ${{ vars.GPG_FAKE_PASSPHRASE }}
          GITHUB_TOKEN: "ACTUAL_YOUR_TOKEN"
        run: |
          curl -O https://raw.githubusercontent.com/pgrange/bash_unit/master/bash_unit
          FORCE_COLOR=true ./bash_unit tests/**/*.test.sh
